name: PR Title Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

permissions:
  contents: none

jobs:
  check-length:
    name: Check length
    runs-on: ubuntu-20.04

    steps:
      - name: Check length
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [ $(echo -n "${PR_TITLE} (#${PR_NUM})" | wc -c) -gt 72 ]
          then
            MAX_CHARS="$((72 - $(echo -n " (#${PR_NUM})" | wc -c)))"
            echo PR title cannot be longer than ${MAX_CHARS} characters
            exit 1
          else
            echo PR title passed the length check
          fi
